### ISSUE TITLE
Corporate proxy workaround

### ISSUE THREAD

**Issue by bohdanszymanik** [OlegZee/Suave.OAuth#1]
Noticed our corporate proxy getting in the way and requesting authentication. Usual response with .net apps is either add a proxy setting in the config file or do something like this in HttpCli.fs:

```
    request.Proxy.Credentials <- CredentialCache.DefaultCredentials
```

This works fine on my work pc and I'm guessing to get it working ok in the case where there isn't a proxy it would just be prefaced with a not null check         if not(isNull(request.Proxy)) then ...

**Comment by OlegZee** [comment]
Good point. I'm thinking about exposing request so that you could customize it for authorization request. The other reason is that some oauth providers require specific headers to be passed.

**Comment by OlegZee** [comment]
Please check 0.2.1, which allows you customize request as follows:

``` fsharp
       defineProviderConfigs (function
        | "google" -> fun c ->
            {c with
                client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
                client_secret = "yyyyyyyyyyyyyyyyyyyyyyy"
                customize_req = (fun req ->
                    request.Proxy.Credentials <- CredentialCache.DefaultCredentials)
            }
```

**Comment by bohdanszymanik** [comment]
Get the 407 error again. I did as above - although it's req not request.
        customize_req = (fun req ->
                        req.Proxy.Credentials <- System.Net.CredentialCache.DefaultCredentials)
                    }

The error was on this line in HttpCli.fs
        use stream = request.GetRequestStream()
-       $exception  {"The remote server returned an error: (407) Proxy Authentication Required."}   System.Exception {System.Net.WebException}

Looking at the Locals window shows the Proxy.Credentials were null still
