### ISSUE TITLE
User Authenticated at the application level not session level

### ISSUE THREAD

**Issue by monkieboy** [OlegZee/Suave.OAuth#3]
I am experiencing a strange situation that when I authenticate with Facebook on one device, then go to second device unconnected to my Facebook account and browse the website, I see a notification, on the second device, that I am already logged in.

I am ready to be told I am doing something stupidly wrong, but please can you confirm with the example I have given what I may be doing wrong/misunderstanding, if anything.

To reproduce; 
1) Set up Facebook credentials, 
2) Take the example Suave.OAuth project
3) Configure with the Facebook credentials.
4) Hosted the app (I had mine on an azure vm on port 80)
5) Browse the website on device 1
6) Browse on someone else's device (device 2 or private browse).
7) Then log in on device 1 
8) Refresh the web page on device 2 (or private browse)
9) It then shows that I am logged in on both devices (web browser sessions)

```
open Suave
open Suave.Operators
open Suave.Filters
open Suave.Successful
open Suave.Web
open Suave.DotLiquid
open System
open Suave.OAuth

type AppModel =
    {
    mutable name: string
    mutable logged_id: string
    mutable logged_in: bool
    mutable provider: string
    mutable providers: string[]
    }

[<EntryPoint>]
let main argv =

    let model = {
        name = "olegz"; logged_id = ""; logged_in = false
        provider = ""
        providers = [| "Facebook" |]
        }

    let oauthConfigs  =
      defineProviderConfigs 
        (fun pname c ->
          { c with
              client_id = "<fb_id_here>"
              client_secret = "<fb_secret_here>" } )

    let app =
        choose [
            path "/" >=> page "main.html" model

            OAuth.authorize oauthConfigs
                (fun loginData ->

                    model.logged_in <- true
                    model.logged_id <- sprintf "%s (name: %s)" loginData.Id loginData.Name

                    Redirection.FOUND "/"
                )
                (fun () ->

                    model.logged_id <- ""
                    model.logged_in <- false

                    Redirection.FOUND "/"
                )
                (fun error -> OK <| sprintf "Authorization failed because of `%s`" error.Message)

            OAuth.protectedPart
                (choose [
                    path "/protected" >=> GET >=> OK "You've accessed protected part!"
                ])
                (RequestErrors.FORBIDDEN "You do not have access to that application part (/protected)")

            // we'll never get here
            (OK "Hello World!")
        ]
    let port = 80us
    startWebServer  { defaultConfig with bindings = [ Http.HttpBinding.mk HTTP Net.IPAddress.Any port ] } app
    0

```

**Comment by OlegZee** [comment]
Mark,

code looks fine.
The behaviour looks really weird. Suave.OAuth sits on top of Suave’s cookie-based sessions/authentication facility and it could not bring such weirdness. Let me check your scenario @home.

Besides that just wanted to share my intentions. I would like not to use Suave’s authorize and create my own implementation and then control all aspects. This sounds challenging and that is security-critical part. This is good excuse for procrastinating it for months :)

Oleg.

**Comment by monkieboy** [comment]
Thanks Oleg, 

I thought I was going mad. I will await your own investigation, let me know how, if possible I might be able to assist.

Mark

**Comment by OlegZee** [comment]
@monkieboy I cannot compile the example here and I cannot understand/remember what is going on with .NET Fwk version, FSharp.Core and so on.

While the good point is that the reason is in a sample application. See the **model** instance is an application-wide variable, so once you login at one PC it gets filled with your login data. But user will not be able to access protected part.

After you open site from other device, the main.html is rendered and it (as you can see from the code) will render **model** state which indicates user is logged in by that moment.

In real application you should store that data to session storage and that won't happen. E.g. in my application I'm doing it as follows:

``` fsharp
let sessionStore setF = context (fun x ->
        match HttpContext.state x with
        | Some state -> setF state
        | None -> RequestErrors.BAD_REQUEST "damn it")
let authorizeAndCreateSession (sessionInfo : SessionInfo) :WebPart =
        Authentication.authenticated Cookie.CookieLife.Session false
        >=> statefulForSession
        >=> sessionStore (fun store ->
            store.set "userid" sessionInfo.UserId >=>
            store.set "login" sessionInfo.LoginName >=>
            store.set "wall" sessionInfo.WallFeedId)
```
